-- Generated by src/generate-ms-description-sql.js
-- Source: descriptions.json (76 entries)
-- Applies MS_Description extended properties to tables/views.
-- Idempotent: updates if present, inserts if missing.
-- Notes:
--   * @level1type = 'TABLE' is correct for both tables AND views in SQL Server.
--   * Run with sqlcmd: sqlcmd -S <server> -U <user> -P <pwd> -i apply-descriptions.sql
--   * Wrap in BEGIN TRAN / COMMIT manually if you want all-or-nothing semantics.

SET NOCOUNT ON;
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Requisitions', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Header record for every purchase request created in EDS. One row per requisition; line items live in `Detail`. Drives the approval workflow that ultimately produces a PO. Belongs to a District and originating User.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Requisitions';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Header record for every purchase request created in EDS. One row per requisition; line items live in `Detail`. Drives the approval workflow that ultimately produces a PO. Belongs to a District and originating User.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Requisitions';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Detail', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Line items for both requisitions and purchase orders — ~30M rows, the largest transactional table in the procurement chain. Each row links back to its `Requisitions` (and after conversion, to its `PO`) and references either a vendor catalog item via `CrossRefs` or a free-text entry. Pricing, quantities, and account distribution all live here.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Detail';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Line items for both requisitions and purchase orders — ~30M rows, the largest transactional table in the procurement chain. Each row links back to its `Requisitions` (and after conversion, to its `PO`) and references either a vendor catalog item via `CrossRefs` or a free-text entry. Pricing, quantities, and account distribution all live here.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Detail';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Approvals', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Per-step approval audit trail (~8M rows). Records who approved or rejected each requisition at each level of the district''s approval chain, with timestamp and any comment. Combined with `PendingApprovals` to drive the queue an approver sees in the UI.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Approvals';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Per-step approval audit trail (~8M rows). Records who approved or rejected each requisition at each level of the district''s approval chain, with timestamp and any comment. Combined with `PendingApprovals` to drive the queue an approver sees in the UI.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Approvals';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'PendingApprovals', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Active work queue — one row per (requisition, approver) pair currently awaiting action. Rows are deleted as approvers act; historical record is preserved in `Approvals`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PendingApprovals';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Active work queue — one row per (requisition, approver) pair currently awaiting action. Rows are deleted as approvers act; historical record is preserved in `Approvals`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PendingApprovals';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'PO', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Purchase order header (~2.5M rows). Created when a requisition reaches final approval and is converted. One PO has many `PODetailItems` lines and references the originating `Requisitions` row 1:1.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PO';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Purchase order header (~2.5M rows). Created when a requisition reaches final approval and is converted. One PO has many `PODetailItems` lines and references the originating `Requisitions` row 1:1.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PO';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'PODetailItems', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'PO line-item detail (~24.5M rows). Snapshot of item, quantity, unit price, and account split at the moment of PO issuance. Independent from `Detail` — Detail can change after PO issuance, PODetailItems is the immutable contractual record.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PODetailItems';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'PO line-item detail (~24.5M rows). Snapshot of item, quantity, unit price, and account split at the moment of PO issuance. Independent from `Detail` — Detail can change after PO issuance, PODetailItems is the immutable contractual record.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PODetailItems';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'POStatus', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Lookup table of PO lifecycle states (open, partial, received, closed, voided, etc.) joined to `PO` via status code.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'POStatus';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Lookup table of PO lifecycle states (open, partial, received, closed, voided, etc.) joined to `PO` via status code.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'POStatus';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'RequisitionChangeLog', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Append-only audit log of edits to requisition headers and lines (~1.9M rows). Captures field-level before/after values with user and timestamp. Used for the requisition history view.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'RequisitionChangeLog';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Append-only audit log of edits to requisition headers and lines (~1.9M rows). Captures field-level before/after values with user and timestamp. Used for the requisition history view.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'RequisitionChangeLog';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'DetailChangeLog', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Append-only audit log of edits to `Detail` rows (~2.9M rows). Same structure as `RequisitionChangeLog` but scoped to line items.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'DetailChangeLog';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Append-only audit log of edits to `Detail` rows (~2.9M rows). Same structure as `RequisitionChangeLog` but scoped to line items.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'DetailChangeLog';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Vendors', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Master vendor record — supplier directory for the whole platform (~19K rows). One row per vendor company. The `Active` column (tinyint) gates whether a vendor''s catalogs and bid responses are visible to buyers; mutating it has system-wide effect.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Vendors';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Master vendor record — supplier directory for the whole platform (~19K rows). One row per vendor company. The `Active` column (tinyint) gates whether a vendor''s catalogs and bid responses are visible to buyers; mutating it has system-wide effect.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Vendors';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'VendorContacts', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Named contacts (sales reps, AP contacts, etc.) attached to a vendor. Used for PO routing, bid notifications, and dispute correspondence.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'VendorContacts';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Named contacts (sales reps, AP contacts, etc.) attached to a vendor. Used for PO routing, bid notifications, and dispute correspondence.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'VendorContacts';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'VendorUploads', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Log of every vendor catalog or pricing file submitted (~1.5M rows). Tracks file name, vendor, upload type, status, and the eventual import result. Direct writes to `CrossRefs` should always trace back to a row here.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'VendorUploads';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Log of every vendor catalog or pricing file submitted (~1.5M rows). Tracks file name, vendor, upload type, status, and the eventual import result. Direct writes to `CrossRefs` should always trace back to a row here.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'VendorUploads';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Catalog', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor-published catalog — a named container that groups a set of `CrossRefs` entries (~4K rows). One vendor may publish multiple catalogs (e.g., per product line or per bid award).',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Catalog';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor-published catalog — a named container that groups a set of `CrossRefs` entries (~4K rows). One vendor may publish multiple catalogs (e.g., per product line or per bid award).',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Catalog';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'CrossRefs', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor-item cross-reference (~171M rows — by far the hottest table in EDS). Maps a vendor''s part number to an EDS `Items` master record with vendor-specific price, pack size, and effective dates. This is where pricing actually lives. Always filter or `TOP n` when querying — full scans are catastrophic.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'CrossRefs';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor-item cross-reference (~171M rows — by far the hottest table in EDS). Maps a vendor''s part number to an EDS `Items` master record with vendor-specific price, pack size, and effective dates. This is where pricing actually lives. Always filter or `TOP n` when querying — full scans are catastrophic.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'CrossRefs';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Items', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Master product catalog (~44M rows) — normalized, vendor-agnostic items that vendor offerings link to via `CrossRefs`. Categorized by `Category` and (where applicable) attributed to a `Manufacturers` record.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Items';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Master product catalog (~44M rows) — normalized, vendor-agnostic items that vendor offerings link to via `CrossRefs`. Categorized by `Category` and (where applicable) attributed to a `Manufacturers` record.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Items';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Category', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Top-level product taxonomy (~134 rows). Small, stable lookup — used for browse, reporting rollups, and price-plan scoping.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Category';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Top-level product taxonomy (~134 rows). Small, stable lookup — used for browse, reporting rollups, and price-plan scoping.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Category';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Manufacturers', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Manufacturer/brand directory (~9K rows). Note the legacy column spelling `Manufacturor` appears in some related tables — see quirks reference. Items reference a manufacturer; vendors do not.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Manufacturers';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Manufacturer/brand directory (~9K rows). Note the legacy column spelling `Manufacturor` appears in some related tables — see quirks reference. Items reference a manufacturer; vendors do not.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Manufacturers';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidHeaders', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Bid solicitation header (~9.6K rows). One row per RFP/IFB/cooperative bid issued to vendors. Drives the bid-response window and ultimately produces `Awards`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidHeaders';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Bid solicitation header (~9.6K rows). One row per RFP/IFB/cooperative bid issued to vendors. Drives the bid-response window and ultimately produces `Awards`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidHeaders';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidHeaderDetail', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Per-line bid specifications (~123M rows — second-largest table in EDS). Holds the items, specs, and quantities a bid is asking vendors to price. Always filter by `BidHeaderId` before any analytical work.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidHeaderDetail';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Per-line bid specifications (~123M rows — second-largest table in EDS). Holds the items, specs, and quantities a bid is asking vendors to price. Always filter by `BidHeaderId` before any analytical work.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidHeaderDetail';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidRequestItems', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Items the bid is asking about (~27.9M rows) — paired with `BidHeaderDetail` to define the buy. Vendor responses to these line items land in `BidResults`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidRequestItems';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Items the bid is asking about (~27.9M rows) — paired with `BidHeaderDetail` to define the buy. Vendor responses to these line items land in `BidResults`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidRequestItems';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidItems', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Master list of items eligible to appear on bids (~27.5M rows). Distinct from `BidRequestItems` (request-time snapshot) — this is the catalog side.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidItems';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Master list of items eligible to appear on bids (~27.5M rows). Distinct from `BidRequestItems` (request-time snapshot) — this is the catalog side.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidItems';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Bids', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor bid response header (~147K rows). One row per (bid, vendor) submission, indicating intent to respond and submission status. Line-by-line responses are in `BidResults`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Bids';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor bid response header (~147K rows). One row per (bid, vendor) submission, indicating intent to respond and submission status. Line-by-line responses are in `BidResults`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Bids';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidResults', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor line-item bid responses (~33.2M rows) — the prices, lead times, and notes a vendor submitted for each `BidRequestItems` line they chose to bid on.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidResults';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor line-item bid responses (~33.2M rows) — the prices, lead times, and notes a vendor submitted for each `BidRequestItems` line they chose to bid on.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidResults';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Awards', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Bid award outcomes (~139K rows). Records which vendor''s `BidResults` were chosen for each awarded line, including award date and award type. Awarded prices typically flow back into `CrossRefs` via a vendor catalog upload.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Awards';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Bid award outcomes (~139K rows). Records which vendor''s `BidResults` were chosen for each awarded line, including award date and award type. Awarded prices typically flow back into `CrossRefs` via a vendor catalog upload.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Awards';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidAnswers', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor responses to non-pricing bid questions (~552K rows) — terms, certifications, attribute confirmations.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidAnswers';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor responses to non-pricing bid questions (~552K rows) — terms, certifications, attribute confirmations.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidAnswers';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'District', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Master record for a participating school district or other public entity (~979 rows). Top of the customer hierarchy. Budgets, approval chains, and price plans attach here. Treat as effectively static — bulk changes propagate everywhere.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'District';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Master record for a participating school district or other public entity (~979 rows). Top of the customer hierarchy. Budgets, approval chains, and price plans attach here. Treat as effectively static — bulk changes propagate everywhere.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'District';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'School', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Schools/buildings beneath a district (~6.6K rows). Used for ship-to address and reporting rollups; not a security boundary.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'School';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Schools/buildings beneath a district (~6.6K rows). Used for ship-to address and reporting rollups; not a security boundary.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'School';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Users', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Master user directory (~345K rows) — every person with login or named-recipient status across all districts. `Active` flag controls login eligibility; deletion is rare (audit references).',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Users';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Master user directory (~345K rows) — every person with login or named-recipient status across all districts. `Active` flag controls login eligibility; deletion is rare (audit references).',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Users';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'UserAccounts', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Per-user budget account permissions (~3.4M rows). Joins users to the `BudgetAccounts` they''re allowed to charge against. Drives the account dropdown shown when building a requisition.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'UserAccounts';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Per-user budget account permissions (~3.4M rows). Joins users to the `BudgetAccounts` they''re allowed to charge against. Drives the account dropdown shown when building a requisition.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'UserAccounts';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BudgetAccounts', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'District budget accounts / charge codes (~1.4M rows). Hierarchical (often fund-function-object), district-scoped. Requisition lines distribute against rows here.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BudgetAccounts';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'District budget accounts / charge codes (~1.4M rows). Hierarchical (often fund-function-object), district-scoped. Requisition lines distribute against rows here.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BudgetAccounts';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'PricePlans', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Named price-plan definitions (~585 rows) — controls which categories/vendors are visible to which districts at what pricing tier. Small but pivotal: changes here change what buyers see.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PricePlans';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Named price-plan definitions (~585 rows) — controls which categories/vendors are visible to which districts at what pricing tier. Small but pivotal: changes here change what buyers see.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PricePlans';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Audit', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Generic audit log (~2.6M rows) — application-level events (logins, permission changes, data exports, admin actions). Distinct from the change-log tables, which are field-level.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Audit';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Generic audit log (~2.6M rows) — application-level events (logins, permission changes, data exports, admin actions). Distinct from the change-log tables, which are field-level.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Audit';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'TransactionLog_HISTORY', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Long-tail historical event log (~124M rows). Cold storage — query with date filters and expect slow reads. Rarely needed for operational work; kept for compliance.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'TransactionLog_HISTORY';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Long-tail historical event log (~124M rows). Cold storage — query with date filters and expect slow reads. Rarely needed for operational work; kept for compliance.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'TransactionLog_HISTORY';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'OrderBookDetail', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Aggregated order/spending facts used by reporting (~37.8M rows). Fed from completed `PODetailItems`. The `OrderBookDetailOld` table (~187M rows) is the prior-format archive — read but do not write.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'OrderBookDetail';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Aggregated order/spending facts used by reporting (~37.8M rows). Fed from completed `PODetailItems`. The `OrderBookDetailOld` table (~187M rows) is the prior-format archive — read but do not write.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'OrderBookDetail';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'OrderBookDetailOld', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Legacy archive of `OrderBookDetail` (~187M rows). Read-only; all new spend rolls up into `OrderBookDetail`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'OrderBookDetailOld';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Legacy archive of `OrderBookDetail` (~187M rows). Read-only; all new spend rolls up into `OrderBookDetail`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'OrderBookDetailOld';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'ReportSession', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'User-facing report executions (~5.4M rows) — what reports were run, by whom, with which parameters.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'ReportSession';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'User-facing report executions (~5.4M rows) — what reports were run, by whom, with which parameters.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'ReportSession';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'ReportSessionLinks', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Per-session output links (~52.7M rows) — joins a report session to the rows it generated, used to support drill-throughs and saved exports.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'ReportSessionLinks';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Per-session output links (~52.7M rows) — joins a report session to the rows it generated, used to support drill-throughs and saved exports.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'ReportSessionLinks';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BatchDetail', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Staging table for batch-imported requisition / order detail (~5M rows). Holds raw character-typed values (`OrigType`, `OrigDistrictCode`, `OrigCometCode`, `OrigItemCode`, `OrigQuantity`) alongside their resolved IDs so the importer can report and back-out errors. `ErrorField` flags malformed rows.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BatchDetail';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Staging table for batch-imported requisition / order detail (~5M rows). Holds raw character-typed values (`OrigType`, `OrigDistrictCode`, `OrigCometCode`, `OrigItemCode`, `OrigQuantity`) alongside their resolved IDs so the importer can report and back-out errors. `ErrorField` flags malformed rows.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BatchDetail';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidProductLinePrices', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Manufacturer product-line discount tiers offered by a vendor on a bid (~1.3M rows). `RangeBase` is the dollar floor for the tier; `DiscountRate` is the percent off list. Joins a `BidProductLines` row to its tiered pricing structure.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidProductLinePrices';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Manufacturer product-line discount tiers offered by a vendor on a bid (~1.3M rows). `RangeBase` is the dollar floor for the tier; `DiscountRate` is the percent off list. Joins a `BidProductLines` row to its tiered pricing structure.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidProductLinePrices';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidMappedItems', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Audit of item remapping decisions made during bid setup. Records the original `OrigItemId`, the chosen `NewItemId`, a `ReasonCode`, and the date — so award lineage stays explicit when a bid line is re-pointed at a different master item.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidMappedItems';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Audit of item remapping decisions made during bid setup. Records the original `OrigItemId`, the chosen `NewItemId`, a `ReasonCode`, and the date — so award lineage stays explicit when a bid line is re-pointed at a different master item.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidMappedItems';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidRequestPriceRanges', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Quantity / dollar tier definitions a bid is asking vendors to price against (~1.9M rows). Tied to a `BidHeaderId` and (optionally) a manufacturer/product-line, with a `RangeBase` floor and `RangeWeight` used to compute the weighted bid score.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidRequestPriceRanges';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Quantity / dollar tier definitions a bid is asking vendors to price against (~1.9M rows). Tied to a `BidHeaderId` and (optionally) a manufacturer/product-line, with a `RangeBase` floor and `RangeWeight` used to compute the weighted bid score.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidRequestPriceRanges';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidAnswersJournal', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Append-only change history for `BidAnswers` (~1.3M rows). Captures the prior value, session, and modification timestamp every time a vendor edits a non-pricing bid response.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidAnswersJournal';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Append-only change history for `BidAnswers` (~1.3M rows). Captures the prior value, session, and modification timestamp every time a vendor edits a non-pricing bid response.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidAnswersJournal';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidMSRPResultPrices', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Per-tier MSRP-discount results submitted by a vendor on an MSRP-style bid (~423K rows). One row per `BidRequestPriceRange` per vendor result, with the discount-applied price.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidMSRPResultPrices';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Per-tier MSRP-discount results submitted by a vendor on an MSRP-style bid (~423K rows). One row per `BidRequestPriceRange` per vendor result, with the discount-applied price.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidMSRPResultPrices';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BidRequestOptions', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Optional bid-line attributes per (manufacturer, product line) — color, capacity, etc. Each row weights one named option for use in vendor evaluation.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidRequestOptions';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Optional bid-line attributes per (manufacturer, product line) — color, capacity, etc. Each row weights one named option for use in vendor evaluation.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BidRequestOptions';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'EmailBlastLog', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Audit of every transactional / marketing email sent from the platform (~1.5M rows). Captures sender, recipient, CC/BCC, send date, and the rendered XML payload. `Attachment` is the file name, not the content.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'EmailBlastLog';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Audit of every transactional / marketing email sent from the platform (~1.5M rows). Captures sender, recipient, CC/BCC, send date, and the rendered XML payload. `Attachment` is the file name, not the content.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'EmailBlastLog';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'ImportDetail', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Raw rows captured from a generic file import (~883K rows). One row of `ImportData` per source line, scoped to an `ImportId` header. Read after parsing to inspect malformed input.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'ImportDetail';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Raw rows captured from a generic file import (~883K rows). One row of `ImportData` per source line, scoped to an `ImportId` header. Read after parsing to inspect malformed input.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'ImportDetail';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'IPQueueUsers', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Per-user import-process queue assignments (~490K rows). Tracks `Requested`, `Started`, `Completed` timestamps and `Status` so background work can be parallelized and resumed.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'IPQueueUsers';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Per-user import-process queue assignments (~490K rows). Tracks `Requested`, `Started`, `Completed` timestamps and `Status` so background work can be parallelized and resumed.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'IPQueueUsers';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'POQueueItems', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Outbound PO transmission queue (~401K rows). One row per PO send attempt, with `SendStarted`, `SendEnded`, `SendStatus` and a `PayloadId` referencing the rendered cXML / email body.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'POQueueItems';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Outbound PO transmission queue (~401K rows). One row per PO send attempt, with `SendStarted`, `SendEnded`, `SendStatus` and a `PayloadId` referencing the rendered cXML / email body.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'POQueueItems';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'PricingConsolidatedOrderCounts', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Demand-history counts feeding the consolidated-pricing analytics pipeline (~401K rows). One row per (`BidHeaderId`, `ItemId`) with `OrderCount` — used to weight bid evaluation by realized buying patterns.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PricingConsolidatedOrderCounts';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Demand-history counts feeding the consolidated-pricing analytics pipeline (~401K rows). One row per (`BidHeaderId`, `ItemId`) with `OrderCount` — used to weight bid evaluation by realized buying patterns.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PricingConsolidatedOrderCounts';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'RTK_ReportItems', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'New Jersey Right-To-Know chemical-reporting line items (~1M rows). Joins district + site + category + item + quantity, paired with `RTK_Sites` (locations) and `RTK_Items` (chemical detail). Feeds the annual NJ RTK survey.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'RTK_ReportItems';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'New Jersey Right-To-Know chemical-reporting line items (~1M rows). Joins district + site + category + item + quantity, paired with `RTK_Sites` (locations) and `RTK_Items` (chemical detail). Feeds the annual NJ RTK survey.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'RTK_ReportItems';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'DetailNotifications', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Buyer-facing notifications about line-item changes (~3M rows). When a vendor substitutes or replaces an item the system writes a row here capturing the original vs. new `ItemId`, `VendorId`, and `BidPrice` so the buyer can review.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'DetailNotifications';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Buyer-facing notifications about line-item changes (~3M rows). When a vendor substitutes or replaces an item the system writes a row here capturing the original vs. new `ItemId`, `VendorId`, and `BidPrice` so the buyer can review.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'DetailNotifications';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'TaskSchedule', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Bid-cycle / pricing-cycle work schedule (~1.5M rows). Tracks original, projected, and actual start/end dates for each task in a project, scoped by district, category, and price plan.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'TaskSchedule';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Bid-cycle / pricing-cycle work schedule (~1.5M rows). Tracks original, projected, and actual start/end dates for each task in a project, scoped by district, category, and price plan.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'TaskSchedule';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'SessionTable', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Active and recent user-session state (~12.8M rows). Holds the user''s current district, school, requisition, PO, budget, mode, and screen state. Hot during business hours; queried heavily on every page load.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'SessionTable';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Active and recent user-session state (~12.8M rows). Holds the user''s current district, school, requisition, PO, budget, mode, and screen state. Hot during business hours; queried heavily on every page load.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'SessionTable';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'DMSVendorBidDocuments', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Document metadata for vendor bid attachments stored in the document-management system (~750K rows). One row per uploaded file with `DocType`, `ExpirationDate`, page count, and a `DocId` GUID pointing into DMS storage.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'DMSVendorBidDocuments';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Document metadata for vendor bid attachments stored in the document-management system (~750K rows). One row per uploaded file with `DocType`, `ExpirationDate`, page count, and a `DocId` GUID pointing into DMS storage.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'DMSVendorBidDocuments';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'CatalogTextParts', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Tokenized catalog text for full-text search (~17M rows). One row per text fragment per `CatalogText` entry with a `BaseOffset` so the original text can be reassembled. Rebuilt during catalog imports.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'CatalogTextParts';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Tokenized catalog text for full-text search (~17M rows). One row per text fragment per `CatalogText` entry with a `BaseOffset` so the original text can be reassembled. Rebuilt during catalog imports.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'CatalogTextParts';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'HeaderWorkItems', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Working set of items being aggregated into an OrderBook header (~492K rows). Transient — populated during OrderBook generation and emptied when the run completes.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'HeaderWorkItems';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Working set of items being aggregated into an OrderBook header (~492K rows). Transient — populated during OrderBook generation and emptied when the run completes.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'HeaderWorkItems';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'VMS', N'TABLE', 'vw_Login', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor-portal login lookup view. Used by the vendor-management UI to authenticate and resolve a vendor''s accessible bids.',
        @level0type = N'SCHEMA', @level0name = 'VMS',
        @level1type = N'TABLE',  @level1name = 'vw_Login';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor-portal login lookup view. Used by the vendor-management UI to authenticate and resolve a vendor''s accessible bids.',
        @level0type = N'SCHEMA', @level0name = 'VMS',
        @level1type = N'TABLE',  @level1name = 'vw_Login';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'VMS', N'TABLE', 'vw_BidsByVendor', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor-portal view listing bids visible to each vendor — the per-vendor cut of `BidHeaders` joined with award status. Drives the vendor''s bid-list screen.',
        @level0type = N'SCHEMA', @level0name = 'VMS',
        @level1type = N'TABLE',  @level1name = 'vw_BidsByVendor';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Vendor-portal view listing bids visible to each vendor — the per-vendor cut of `BidHeaders` joined with award status. Drives the vendor''s bid-list screen.',
        @level0type = N'SCHEMA', @level0name = 'VMS',
        @level1type = N'TABLE',  @level1name = 'vw_BidsByVendor';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'EDSIQWebUser', N'TABLE', 'OrderBookView', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Reporting view over consolidated order data — top-level grain, suitable for dashboard summaries.',
        @level0type = N'SCHEMA', @level0name = 'EDSIQWebUser',
        @level1type = N'TABLE',  @level1name = 'OrderBookView';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Reporting view over consolidated order data — top-level grain, suitable for dashboard summaries.',
        @level0type = N'SCHEMA', @level0name = 'EDSIQWebUser',
        @level1type = N'TABLE',  @level1name = 'OrderBookView';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'EDSIQWebUser', N'TABLE', 'OrderBookDetailView', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Reporting view exposing line-level OrderBook detail — the drill-through target from `OrderBookView`.',
        @level0type = N'SCHEMA', @level0name = 'EDSIQWebUser',
        @level1type = N'TABLE',  @level1name = 'OrderBookDetailView';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Reporting view exposing line-level OrderBook detail — the drill-through target from `OrderBookView`.',
        @level0type = N'SCHEMA', @level0name = 'EDSIQWebUser',
        @level1type = N'TABLE',  @level1name = 'OrderBookDetailView';
GO

USE [EDS];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'EDSIQWebUser', N'TABLE', 'POAccountList', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Reporting view listing PO line items by budget account — used for budget-utilization reports.',
        @level0type = N'SCHEMA', @level0name = 'EDSIQWebUser',
        @level1type = N'TABLE',  @level1name = 'POAccountList';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Reporting view listing PO line items by budget account — used for budget-utilization reports.',
        @level0type = N'SCHEMA', @level0name = 'EDSIQWebUser',
        @level1type = N'TABLE',  @level1name = 'POAccountList';
GO

USE [Catalogs];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Master Catalog', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Consolidated cross-vendor master catalog used as the import target for catalog file processing (~144M rows — the largest table on the server). Read-heavy; rebuilt by the catalog-import pipeline.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Master Catalog';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Consolidated cross-vendor master catalog used as the import target for catalog file processing (~144M rows — the largest table on the server). Read-heavy; rebuilt by the catalog-import pipeline.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Master Catalog';
GO

USE [Catalogs];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'CatalogImports', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Catalog-import job audit (~405 rows) — one row per upload run, capturing source, status, and outcome counts.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'CatalogImports';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Catalog-import job audit (~405 rows) — one row per upload run, capturing source, status, and outcome counts.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'CatalogImports';
GO

USE [Catalogs];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'uniqueCodes', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Dedup helper for catalog imports (~331K rows) — tracks unique vendor part / item codes already seen so subsequent runs can skip duplicates.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'uniqueCodes';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Dedup helper for catalog imports (~331K rows) — tracks unique vendor part / item codes already seen so subsequent runs can skip duplicates.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'uniqueCodes';
GO

USE [Catalogs];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Grainger Jan 2019', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Frozen snapshot of the Grainger January 2019 catalog feed (~1.5M rows). One of several Grainger snapshots in this DB (`Grainger Jan 2015`, `…Jan 2016`, `…Jan 2017`, `…Jan 2017 Revised`, `…Feb 2018`, `…May 2018`, `…May 2017`, `…May 2016`). Kept for historical pricing comparisons.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Grainger Jan 2019';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Frozen snapshot of the Grainger January 2019 catalog feed (~1.5M rows). One of several Grainger snapshots in this DB (`Grainger Jan 2015`, `…Jan 2016`, `…Jan 2017`, `…Jan 2017 Revised`, `…Feb 2018`, `…May 2018`, `…May 2017`, `…May 2016`). Kept for historical pricing comparisons.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Grainger Jan 2019';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Entities', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Customer entities (districts and other public organizations) participating in cooperative procurement — analytics-side master record. Distinct from `EDS.dbo.District` and includes additional analytics fields like `StudentCount`, `Population`, `Region`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Entities';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Customer entities (districts and other public organizations) participating in cooperative procurement — analytics-side master record. Distinct from `EDS.dbo.District` and includes additional analytics fields like `StudentCount`, `Population`, `Region`.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Entities';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Vendors', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Analytics-side vendor master. Smaller and cleaner than `EDS.dbo.Vendors` — kept in sync via the analytics ETL.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Vendors';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Analytics-side vendor master. Smaller and cleaner than `EDS.dbo.Vendors` — kept in sync via the analytics ETL.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Vendors';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'Contracts', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Cooperative-contract master used for spend analytics. Captures contract value, term, negotiated savings, status, and auto-renew settings per (vendor, contract).',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Contracts';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Cooperative-contract master used for spend analytics. Captures contract value, term, negotiated savings, status, and auto-renew settings per (vendor, contract).',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'Contracts';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'PurchaseOrders', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'PO header — analytics flatten of EDS PO data with denormalized department / cost-center / project-code fields and lifecycle dates.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PurchaseOrders';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'PO header — analytics flatten of EDS PO data with denormalized department / cost-center / project-code fields and lifecycle dates.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PurchaseOrders';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'PurchaseOrderLines', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'PO line detail joined back to its `PurchaseOrders` header. Holds qty, unit price, line total, UoM, and received qty for variance analysis.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PurchaseOrderLines';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'PO line detail joined back to its `PurchaseOrders` header. Holds qty, unit price, line total, UoM, and received qty for variance analysis.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'PurchaseOrderLines';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'SpendTransactions', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Atomic spend events feeding the analytics fact tables. Each row pairs a PO line with a contract (or `IsOffContract = 1` for maverick spend) plus fiscal-period attributes.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'SpendTransactions';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Atomic spend events feeding the analytics fact tables. Each row pairs a PO line with a contract (or `IsOffContract = 1` for maverick spend) plus fiscal-period attributes.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'SpendTransactions';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'EntitySpend', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Bridge linking an `Entity` to a `SpendTransaction` so spend can be rolled up by entity without re-traversing the PO chain.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'EntitySpend';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Bridge linking an `Entity` to a `SpendTransaction` so spend can be rolled up by entity without re-traversing the PO chain.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'EntitySpend';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'VendorPerformance', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Periodic vendor scorecards — on-time-delivery percent, quality, defect rate, responsiveness, cost competitiveness, and overall score. Drives vendor ranking and renewal recommendations.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'VendorPerformance';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Periodic vendor scorecards — on-time-delivery percent, quality, defect rate, responsiveness, cost competitiveness, and overall score. Drives vendor ranking and renewal recommendations.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'VendorPerformance';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'EntityVendors', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Many-to-many of which vendors each entity transacts with, including the relationship start date and a primary-vendor flag.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'EntityVendors';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Many-to-many of which vendors each entity transacts with, including the relationship start date and a primary-vendor flag.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'EntityVendors';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'EntityBudgets', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Per-entity, per-fiscal-year budget allocations by category. `AllocatedAmount` is the original amount; `AmendedAmount` reflects mid-year revisions.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'EntityBudgets';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Per-entity, per-fiscal-year budget allocations by category. `AllocatedAmount` is the original amount; `AmendedAmount` reflects mid-year revisions.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'EntityBudgets';
GO

USE [ProcurementAnalytics];
IF EXISTS (
    SELECT 1 FROM sys.fn_listextendedproperty(
        N'MS_Description', N'SCHEMA', 'dbo', N'TABLE', 'BudgetAllocations', NULL, NULL)
)
    EXEC sp_updateextendedproperty
        @name = N'MS_Description',
        @value = N'Org-level budget allocations (department / cost center / project / category) used as the rollup target for entity-level spend analytics.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BudgetAllocations';
ELSE
    EXEC sp_addextendedproperty
        @name = N'MS_Description',
        @value = N'Org-level budget allocations (department / cost center / project / category) used as the rollup target for entity-level spend analytics.',
        @level0type = N'SCHEMA', @level0name = 'dbo',
        @level1type = N'TABLE',  @level1name = 'BudgetAllocations';
GO

-- Verify with:
-- USE EDS;
-- SELECT s.name AS [schema], o.name AS [object], CAST(ep.value AS NVARCHAR(MAX)) AS description
-- FROM sys.extended_properties ep
-- JOIN sys.objects o ON ep.major_id = o.object_id AND ep.minor_id = 0
-- JOIN sys.schemas s ON o.schema_id = s.schema_id
-- WHERE ep.name = N'MS_Description' AND ep.class = 1
-- ORDER BY s.name, o.name;
